# Generated by Django 4.2.7 on 2023-11-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_userprofile_age_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
